# Generated by Django 5.1.4 on 2025-01-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtTestUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('phone', models.TextField(blank=True, null=True)),
                ('crm', models.TextField(blank=True, null=True)),
                ('telephony', models.TextField(blank=True, null=True)),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
